# Generated by Django 4.0.4 on 2023-04-08 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAgro', '0003_fertilizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='postPlantingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldPreparation', models.CharField(max_length=300)),
                ('depth', models.FloatField()),
                ('spacing', models.CharField(max_length=200)),
                ('drainage', models.CharField(max_length=200)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyAgro.crops')),
            ],
        ),
    ]
