# Generated by Django 4.0.4 on 2023-04-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAgro', '0004_postplantingprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseName', models.CharField(max_length=150)),
                ('advice', models.CharField(max_length=300)),
                ('pesticides', models.CharField(max_length=200)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyAgro.crops')),
            ],
        ),
    ]
