# Generated by Django 4.0.4 on 2023-04-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAgro', '0005_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='prePlantingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('spacing', models.CharField(max_length=200)),
                ('irrigation', models.CharField(max_length=400)),
                ('drainage', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyAgro.crops')),
            ],
        ),
    ]
