# Generated by Django 4.0.4 on 2023-04-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAgro', '0006_preplantingprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplantingprocess',
            name='irrigation',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
