# Generated by Django 4.0.4 on 2023-05-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAgro', '0010_postplantingprocess_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postplantingprocess',
            name='time',
        ),
    ]
