# Generated by Django 4.0.4 on 2023-05-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAgro', '0012_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='currentK',
        ),
        migrations.RemoveField(
            model_name='project',
            name='currentN',
        ),
        migrations.RemoveField(
            model_name='project',
            name='currentP',
        ),
    ]
