# Generated by Django 4.0.4 on 2023-05-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyAgro', '0013_remove_project_currentk_remove_project_currentn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplantingprocess',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
